# Generated by Django 4.2.11 on 2024-07-07 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='Username'),
        ),
    ]
