# Generated by Django 4.2.11 on 2024-06-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
            },
        ),
        migrations.CreateModel(
            name='HostingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('short_description', models.CharField(max_length=255, verbose_name='Short description')),
                ('price', models.FloatField(verbose_name='Price')),
                ('real_price', models.FloatField(default=0, verbose_name='Real price')),
                ('sale', models.BooleanField(default=False, verbose_name='Sale')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='Discount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('opportunity', models.ManyToManyField(related_name='hosting', to='hostings.opportunitymodel', verbose_name='Opportunity')),
            ],
            options={
                'verbose_name': 'Hosting',
                'verbose_name_plural': 'List of hosting',
            },
        ),
    ]
